# Describes the format for available bpost services

add_tracking:
  description: Add new tracking to TrackTry.
  fields:
    new_json_array:
      description: Tracking number for the new tracking
      example: '[{"code":"323212505100043382188030", "postalCode":"2360"}]'


remove_tracking:
  description: Remove a tracking from Tracktry.
  fields:
    tracking_number:
      description: Tracking number of the tracking to remove
      example: "123456789"
    carrier_code:
      description: Carrier Code (carrier) of the tracking to remove
      example: "USPS"